# Generated by Django 4.1.1 on 2022-09-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Phone_Number', models.IntegerField()),
                ('Date', models.CharField(max_length=10)),
                ('Amount_Paid', models.IntegerField()),
            ],
        ),
    ]
